### PR TITLE
feat(cli): XLIFF file loader

### PR DESCRIPTION
**Pull request by Nithishvb**
Resolves: #291

This PR introduces a new loader for XLIFF files within the Replexica project.

### CODE REVIEW

**Comment by maxprilutskiy** [comment]
Hi @Nithishvb – wondering why commits are authored by @replexicabot here, and not you?

**Comment by Nithishvb** [comment]
Hi @maxprilutskiy  It looks like the author credentials were accidentally set to @replexicabot during the initial commits. I've updated the author information now, so it correctly reflects my account. Thanks for catching that!

**Comment by maxprilutskiy** [comment]
hi @Nithishvb thanks for the PR, I appreciate the effort, but I have to close this one as a duplicate of #304 - @partik03 started working on this slightly earlier.

next time, please make sure the ticket is assigned to you before starting work! (just ask in the issue comments)

**Comment by partik03** [comment]
@maxprilutskiy please reopen this one, I closed my PR as it was opened later

**Comment by maxprilutskiy** [comment]
@partik03 ok np! sounds good

**Comment by maxprilutskiy** [comment]
@Nithishvb please check my implemention in #303 + my comments, and update your version, as I'm afraid you aren't handling the xlf format correctly currently

**Comment by maxprilutskiy** [comment]
@Nithishvb please let me know if you're planning to finalize this PR, otherwise I'd like to close it, to let somebody else pick up this task. Thanks!

**Pull request closed without merging**
