### PR TITLE
feat: Removing redundant i18n files if language is dropped from config

### LINKED ISSUE #127: Remove unused i18n files when language is dropped from config
### What
Add a feature to the `replexica i18n` CLI that automatically removes extra i18n files when a supported language is removed from the i18n.json configuration.

### Why
- Keeps the project clean and organized
- Prevents confusion from outdated language files
- Reduces clutter in the codebase
- Saves disk/repo space (minor benefit)

### How
1. Compare the current i18n.json config with the existing i18n files
2. Identify files for languages no longer in the config
3. Remove the unused files

### PR DESCRIPTION
**Pull request by mobley-trent**
Closes #127

### CODE REVIEW

**Comment by mobley-trent** [comment]
@maxprilutskiy kindly review

**Comment by maxprilutskiy** [comment]
@mobley-trent great job! 👏  checking out later this week.

**Comment by maxprilutskiy** [comment]
@mobley-trent reviewed, good job! here's some feedback:

1. Next time please be sure to follow the style guide: you're extensively using `let`, but the existing code uses `const` by default, unless `let` is explicitly required;
2. Comments are always good in open source, you never know what knowledge the next contributor has;
3. You've added a loop over the `buckets` config – that's fine, but right below that code there's another loop that iterates through `buckets`. This is suboptimal, as it increases complexity O(N) -> O(2N) seemingly without a reason.

Having that said, I think the suggested change makes a lot of sense, and addresses the issue. Also, I need your change to unblock me with something that's coming up next :)

So, as an exception I'm accepting your PR as it is, but for the future – please be sure to make your code look like the rest of the codebase. 👌

Thank you for your Pull Request!

**Comment by opiredev** [comment]
The user @mobley-trent has claimed all the rewards in #127 👀 We've notified the reward creators [here](https://github.com/replexica/replexica/issues/127#issuecomment-2271120593).
@mobley-trent make sure you have your [payment account ready](https://app.opire.dev/settings) to receive the payment for your hard work 💪

**Pull request merged**
