### PR TITLE
fix: preserve i18n.json formatting to avoid unnecessary PRs

### PR DESCRIPTION
**Pull request by Aditya-A-G**
**fixes**: #197 

This PR updates the CLI's JSON serializer to detect and respect existing indentation in i18n.json, avoiding unnecessary formatting changes, addressing the core need outlined in #197. Other formatting elements like quote style aren’t needed for this solution.

### CODE REVIEW

**Comment by Aditya-A-G** [comment]
Hey @maxprilutskiy, could you review this PR when you have a moment? Thanks!

**Comment by maxprilutskiy** [comment]
hey @Aditya-A-G – thanks for the PR!

Actually, given some recent changes we made, you can now implement #197 in a much more elegant / easier way.

1. We already have `prettier` among dependecies of this project
2. Prettier has a JS API
3. Upon (re-)saving the `i18n.json` configuration, let's use the prettier config the user *might* already have, and if they don't then let's use the default prettier config. (Our only requirement to the the default fallback is 2 spaces indentation).

Once you finish the implementation, don't forget to run `pnpm new` from the root of the repo, and then add a brief summary of the changes you're making. Your message will then trigger a new npm package release, once the PR is merged, and will become a part of the changelog.

Let me know if this makes sense!

**Comment by Aditya-A-G** [comment]
Yes, that makes sense! I will implement the change using Prettier as you suggested.

**Comment by maxprilutskiy** [comment]
@Aditya-A-G let me know how this goes and if you need any help!

cc @partik03 if you have any opinion here, lmk

**Comment by partik03** [comment]
@maxprilutskiy I tried searching for this using prettier but ``prettier.resolveConfig`` function is an asynchronous function which needs to be awaited to resolve the configuration of the i18n file due to which we will have to handle promises at various instances in the code

edit: check the prettier doc [here](https://prettier.io/docs/en/api.html#prettierresolveconfigfileurlorpath--options)

**Comment by Aditya-A-G** [comment]
will create a fresh pr

**Pull request closed without merging**
