### PR TITLE
docs: add readmes to each of the publishable packages

### PR DESCRIPTION
**Pull request by iftekharanwar**
Also, implemented dynamic routing to ensure compatibility with the Next.js pages router.

### CODE REVIEW

**Review by maxprilutskiy — CHANGES_REQUESTED** [review]
Great job, @iftekharanwar! 👏 👏 👏 

Please revert the changes made to the `pnpm-lock.yaml` file, and let's merge your PR!

There's been no changes to neither of the repo's packages, so it's ok for `pnpm-lock.yaml` to remain unchanged, and also the diff is quite large hence it's very hard to review.

**Comment by iftekharanwar** [comment]
I've reverted the changes to the `pnpm-lock.yaml` file as requested. Let me know if there's anything else needed, thank you!

**Review by maxprilutskiy — APPROVED** [review]
LGTM!

**Comment by maxprilutskiy** [comment]
Merged, thanks @iftekharanwar !

**Pull request merged**
